version: '3'

services:
  webserver:
    container_name: Products-RESTapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: KBk9CuNj4vK4bPUULlqemF
      MYSQL_DATABASE: products-restapi
    volumes:
      - ./products-restapi/products.sql:/docker-entrypoint-initdb.d/products.sql
    ports:
      - "3306:3306"
