version: '3'

services:
  webserver:
    container_name: Products-RESTapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4300:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: productsrestapi
      MYSQL_USER: productsrestapi
      MYSQL_PASSWORD: KBk9CuNj4vK4bPUULlqemF
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./products.sql:/docker-entrypoint-initdb.d/products.sql
    ports:
      - "3310:3306"
