version: '3'

services:
  webserver:
    container_name: Products-RESTapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4300:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: KBk9CuNj4vK4bPUULlqemF
      MYSQL_DATABASE: products-restapi
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3310:3306"
